version: '3.7'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8082}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=dynamodb,dynamodbstreams
      - DEBUG=${DEBUG-}
      - PORT-WEB-UI=${PORT_WEB_UI-}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"