version: "3.2"
services:
  db:
    image: postgres:14.1
    container_name: postgres-wallet
    ports:
      - "5432:5432"
    volumes:
      - postgres-tatu:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet

volumes:
  postgres-wallet:

networks:
  private:
    external:
      name: private
